### ISSUE TITLE
Looks like your code doesn't extract the sub tars.

### ISSUE THREAD

**Issue by songquanpeng** [y2l/tiered-imagenet-tools#4]
Hi, thanks for sharing.
But I meet a problem when using your code.
When I run the following command: `python tiered_imagenet_generator.py --tar_dir [your_path_of_the_ILSVRC2012_img_train.tar]`, I got many lines of `0it [00:00, ?it/s]`. After checking your code, I think it does not extract the sub tars automatically:
![image](https://user-images.githubusercontent.com/39998050/93992911-b6c2f680-fdc0-11ea-9c51-6637537209db.png)

I tested it on both Windows and Linux (Ubuntu 20.04).
In the end, I think you should mention that users should manually extract the sub tars in the repo's readme.

Thanks.

**Comment by yaoyao-liu** [comment]
Thanks for reporting this issue.
I'll fix this later.
Welcome to create a pull request if you may fix this problem.
